ART_MVC/Controllers/DomainController.cs
using ART_MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.Intrinsics.Arm;

namespace ART_MVC.Controllers
{
    public class DomainController : Controller
    {
        private readonly IConfiguration _configuration;

        public DomainController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            List<DomainViewModel> domainViewModels = new();
            ProjectViewModel projectViewModel = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);

                var result = await client.GetAsync("Domains/GetAllDomains");
                var project = await client.GetAsync($"ProjectsBR/GetProjectBRById/{id}");

                if (result.IsSuccessStatusCode)
                {
                    domainViewModels = await result.Content.ReadAsAsync<List<DomainViewModel>>();
                    domainViewModels = domainViewModels.Where(d => d.ProjectFkId== id).ToList();
                    projectViewModel = await project.Content.ReadAsAsync<ProjectViewModel>();
                    ViewBag.projectName = projectViewModel.ProjectName;
                }

               
            }
            return View(domainViewModels);
        }

        [HttpGet]
        public async Task<IActionResult> Create(int projectId)
        {
           // @(ViewContext.RouteData.Values["id"].ToInt();
            DomainViewModel domainViewModel = new();
            List<ProjectViewModel> projectViewModels = new();
            List<AccountViewModel> accountViewModels = new();
            SignUpViewModel signUpViewModel = new();
            ProjectViewModel projectViewModel = new();
            string empEmail = HttpContext.Session.GetString("empEmail");

            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);

                var result = await client.GetAsync("ProjectsBR/GetAllProjectBRs");
                var allAccounts = await client.GetAsync("AccountsBR/GetAllAccBRs");

                var loggedInEmp = await client.GetAsync($"Accounts/GetEmpId/{empEmail}");

                var project = await client.GetAsync($"ProjectsBR/GetProjectBRById/{projectId}");


                if (result.IsSuccessStatusCode)
                {
                    projectViewModels = await result.Content.ReadAsAsync<List<ProjectViewModel>>();
                    signUpViewModel = await loggedInEmp.Content.ReadAsAsync<SignUpViewModel>();
                    accountViewModels = await allAccounts.Content.ReadAsAsync<List<AccountViewModel>>();
                    projectViewModel = await project.Content.ReadAsAsync<ProjectViewModel>();

                }
            }
            domainViewModel.ProjectViewModels = projectViewModels;
            domainViewModel.AccountViewModels = accountViewModels;
            domainViewModel.EmployeeId = signUpViewModel.Id;
            domainViewModel.ProjectFkId = projectId;
            domainViewModel.ProjectName = projectViewModel.ProjectName;


            return View(domainViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DomainViewModel domainViewModel)
        {

            List<ProjectViewModel> projectViewModels = new();
            List<AccountViewModel> accountViewModels = new();
            SignUpViewModel signUpViewModel = new();
            string empEmail = HttpContext.Session.GetString("empEmail");

            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())

                {
                     domainViewModel.Age = (int)(DateTime.Now - domainViewModel.ApprovedDate).TotalDays;

                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);

                    var result = await client.PostAsJsonAsync("Domains/CreateDomain", domainViewModel);
                    var projects = await client.GetAsync("ProjectsBR/GetAllProjectBRs");
                    var allAccounts = await client.GetAsync("AccountsBR/GetAllAccBRs");
                    var loggedInEmp = await client.GetAsync($"Accounts/GetEmpId/{empEmail}");

                    projectViewModels = await projects.Content.ReadAsAsync<List<ProjectViewModel>>();
                    signUpViewModel = await loggedInEmp.Content.ReadAsAsync<SignUpViewModel>();
                    accountViewModels = await allAccounts.Content.ReadAsAsync<List<AccountViewModel>>();
                    if (result.StatusCode == System.Net.HttpStatusCode.Created)
                    {
                        return RedirectToAction("Index", "ProjectBr");

                    }
                }
            }
            DomainViewModel domainView = new DomainViewModel
            {
                ProjectViewModels = projectViewModels,
                AccountViewModels= accountViewModels,
                SignUpViewModel = signUpViewModel
            };

            // return View(obj);

            return View(domainView);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            DomainViewModel domainViewModel = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Domains/GetDomainById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    domainViewModel = await result.Content.ReadAsAsync<DomainViewModel>();
                    // var cityNameResult = await client.GetAsync($"Cities/GetcityById/{house.CityId}");

                    // var cityName = await cityNameResult.Content.ReadAsAsync<CityViewModel>();

                    // house.CityName = cityName.CityName;
                }
                domainViewModel.Age = (int)(DateTime.Now - domainViewModel.ApprovedDate).TotalDays;
                /*  house.HouseId = id;
                  string houseId = id.ToString();
                  HttpContext.Session.SetString("houseId", houseId);,.L"
                O
  */
            }
            return View(domainViewModel);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            // List<ProjectViewModel> projectViewModels = new();

            if (ModelState.IsValid)
            {
                DomainViewModel domainViewModel = new();
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.GetAsync($"Domains/GetDomainById/{id}");
                   // var projects = await client.GetAsync("ProjectsBR/GetAllProjectBRs");
                    if (result.IsSuccessStatusCode)
                    {
                        domainViewModel = await result.Content.ReadAsAsync<DomainViewModel>();

                        //  movie.Genres = await this.GetGenres();
                        //  masterViewModel.ProjectViewModels = await projects.Content.ReadAsAsync<List<ProjectViewModel>>();
                        domainViewModel.Age = (int)(DateTime.Now - domainViewModel.ApprovedDate).TotalDays;

                        domainViewModel.ProjectName = domainViewModel.ProjectName;
                        domainViewModel.ProjectFkId= domainViewModel.ProjectFkId;
                        domainViewModel.EmployeeId = domainViewModel.EmployeeId;
                        return View(domainViewModel);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Domain doesn't exists");
                    }

                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DomainViewModel domainViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                  

                    // client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                    domainViewModel.Age = (int)(DateTime.Now - domainViewModel.ApprovedDate).TotalDays;

                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PutAsJsonAsync($"Domains/UpdateDomain/{domainViewModel.Id}", domainViewModel);
                    if (result.StatusCode == System.Net.HttpStatusCode.OK && domainViewModel.Age >= 0)
                    {
                        return RedirectToAction("Index","ProjectBr");
                    }
                    else if(domainViewModel.Age < 0)
                    {
                        ModelState.AddModelError("", "Approval date must be today or past.");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Server error..Please try again later.");

                    }
                }
            }
            //MovieViewModel viewModel = new MovieViewModel
            //{
            //    Genres = await this.GetGenres()
            //};
            return View(domainViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                DomainViewModel domainViewModel = null;
                using (var client = new HttpClient())
                {

ART_MVC/Views/Domain/Create.cshtml
@model DomainViewModel
@{
    ViewData["Title"] = "Create";
}
<head>
    <style>
        .field-validation-error {
            color: red;
        }
    </style>
</head>
<div class="container">
    <div class="row">
        <div class="col-md-12 offset-1">


            <div class="col-md-6 align-content-end shadow-lg rounded pl-5 pr-5 pb-3 offset-1">
                <h4 class="card-header-pills">Add Domain Details</h4>
                <form asp-controller="Domain" asp-action="Create" method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>


                    @*                        <input type="hidden" asp-for="UserDetailsId" />
                    *@
                    <input type="hidden" asp-for="EmployeeId" />
                    <input type="hidden" asp-for="ProjectFkId" />
                    <input type="hidden" asp-for="ProjectName" />


                 @*   <div class="form-group">
                        <label asp-for="ProjectId" class="form-label">Project Name</label>
                        <br />
                        <select asp-for="ProjectId" class="dropdown btn btn-outline-dark">
                            <option value="">--Select--</option>
                            @foreach (var project in Model.ProjectViewModels)
                            {
                                <option value="@project.Id">@project.ProjectName</option>
                            }
                        </select>
                        <span asp-validation-for="ProjectId"></span>
                    </div>*@
                    <div class="form-group">
                        <label asp-for="DomainName">Domain Name</label>
                        <input type="text" asp-for="DomainName" placeholder="Enter Name" class="form-control" />
                        <span asp-validation-for="DomainName" class="text-bg-danger"></span>

                    </div>
                    <div class="form-group">
                        <label asp-for="SkillSetRequired">Extra Skills Required</label>
                        <input type="text" asp-for="SkillSetRequired" placeholder="Extra Skills Required" class="form-control" />
                        <span asp-validation-for="SkillSetRequired" class="text-bg-danger"></span>

                    </div>
                    <div class="form-group">
                        <label asp-for="Status">Status</label>
                        <select asp-for="Status" class="dropdown btn btn-outline-dark">
                            <option value="">--Select--</option>
                            <option value="OPEN">OPEN</option>
                            <option value="HOLD">HOLD</option>
                            <option value="CLOSED">CLOSED</option>

                        </select>           
                        <span asp-validation-for="Status" class="text-bg-danger"></span>
                    </div>
                  
                    <div class="form-group">
                        <label asp-for="Grade">Grade</label>
                        <select asp-for="Grade" class="dropdown btn btn-outline-dark">
                            <option value="">--Select--</option>
                            <option value="E1">E1</option>
                            <option value="E2">E2</option>
                            <option value="E3">E3</option>
                            <option value="E4">E4</option>
                           
                        </select>
                        <span asp-validation-for="Grade" class="text-bg-danger"></span>
                    </div>
                

                    <div class="form-group">
                        <label asp-for="ApprovedDate" class="form-label">Approved Date:</label><br />
                        <input type="date" asp-for="ApprovedDate" placeholder="Approved Date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" />
                        <span asp-validation-for="ApprovedDate" class="text-bg-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="No_Of_Positions" class="form-label">Positions Required :</label><br />
                        <input type="text" asp-for="No_Of_Positions" placeholder="postions required" class="form-control" />
                        <span asp-validation-for="No_Of_Positions" class="text-bg-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="JobDescription" class="form-label">Enter Job Description :</label><br />
                        <textarea rows="5" asp-for="JobDescription" class="form-control" placeholder="Enter Job Description">@Model.JobDescription</textarea>
                        <span asp-validation-for="JobDescription" class="text-bg-danger"></span>
                    </div>
                  

                  
                    <br />

                    <div class="form-group">
                        @*<input type="submit" class="=btn btn-dark float-right" value="Add Property" />*@
                        <button type="submit" class="btn btn-dark" value="Add Domain">Add Domain</button>
                    </div>


                </form>

            </div>
        </div>
    </div>
</div>



@section Scripts{

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }
}

ART_MVC/Views/Domain/Delete.cshtml
@model DomainViewModel
@{
    ViewData["Title"] = "Delete";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <div class="card-header"><h3 class="text-center">Delete Project</h3></div><div class="card-body">
                    <img  src="https://cdn.pixabay.com/photo/2012/04/12/22/25/warning-sign-30915__340.png"

                                                 class="" style="margin-left:200px" height="100" width="100" />
                         <p class="text-center mt-3">
                        Are you sure you want to delete this Project?
                    </p>
                    <div class="d-flex justify-content-around">
                        <form asp-controller="Domain" asp-action="Delete" method="post">
                            <button type="submit" class="btn btn-danger">Yes</button>
                        </form>
                        <form asp-controller="ProjectBr" asp-action="Index" method="get">
                            <button type="submit" class="btn btn-danger">No</button>
                        </form>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

ART_MVC/Views/Domain/Details.cshtml
@model DomainViewModel
@{
    ViewData["Title"] = "Details";
}

@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Details";
    var token = Context.Session.GetString("token");
    var empEmail = Context.Session.GetString("empEmail");
}


<h1 class="text-center mt-4 mb-5">Details of @Model.ProjectName</h1>
<a class="btn btn-dark" asp-controller="ProjectBr" asp-action="Index">Back to List</a>
@if (empEmail != null)
{


    <div class="col text-end">
        <a class="btn btn-dark" style="margin-left:90%" asp-controller="Domain" asp-action="Edit" asp-route-id="@Model.Id">Customize</a>
    </div>
}



<table class="table table-hover table-bordered border-primary m-2">
    <thead class="bg-info">
        <tr>
            <th>Project Name</th>
            <th>Approved Date</th>
            <th>Grade</th>
            <th>No Positions Required</th>
            <th>Age</th>

            <th>Skills Required</th>
            <th>Status</th>
            <th>Job Description</th>

        </tr>

    </thead>
    <tbody>
        <tr>
            <td>@Model.ProjectName</td>
              <td>@Model.ApprovedDate.ToShortDateString()</td>
            <td>@Model.Grade</td>
            <td>@Model.No_Of_Positions</td>
            <td>@Model.Age</td>

            <td>@Model.SkillSetRequired</td>

            <td>@Model.Status</td>
            <td>@Model.JobDescription</td>
        </tr>


    </tbody>
</table>

ART_MVC/Views/Domain/Edit.cshtml
@model DomainViewModel
@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 offset-1">


            <div class="col-md-6 align-content-end shadow-lg rounded pl-5 pr-5 pb-3 offset-1">
                <h4 class="card-header-pills">Update Domain Details</h4>
                <form asp-controller="Domain" asp-action="Edit" method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>

                    <input type="hidden" asp-for="@Model.ProjectName" />
                    <input type="hidden" asp-for="@Model.ProjectFkId" />
                    <input type="hidden" asp-for="@Model.EmployeeId" />
                    <input type="hidden" asp-for="@Model.Age" />
                  
                    <div class="form-group">
                        <label asp-for="DomainName">Domain Name</label>
                        <input type="text" asp-for="DomainName" placeholder="Enter Name" class="form-control" />
                        <span asp-validation-for="DomainName" class="text-bg-danger"></span>

                    </div>
                    <div class="form-group">
                        <label asp-for="SkillSetRequired">skills Required</label>
                        <input type="text" asp-for="SkillSetRequired" placeholder="Skills reuired" class="form-control" />
                        <span asp-validation-for="SkillSetRequired" class="text-bg-danger"></span>

                    </div>
                  

                    <div class="form-group">
                        <label asp-for="Status">Status</label>
                        <select asp-for="Status" class="dropdown btn btn-outline-dark w-100">
                            <option value="">--Select--</option>
                            <option value="OPEN">OPEN</option>
                            <option value="HOLD">HOLD</option>
                            <option value="CLOSED">CLOSED</option>
                            <option value="CANCELLED">CANCELLED</option>

                        </select>             
                        <span asp-validation-for="Status" class="text-bg-danger"></span>
                    </div>
                  
                    <div class="form-group">
                        <label asp-for="Grade">Grade</label>
                        <select asp-for="Grade" class="dropdown btn btn-outline-dark w-100">
                            <option value="">--Select--</option>
                            <option value="E1">E1</option>
                            <option value="E2">E2</option>
                            <option value="E3">E3</option>
                            <option value="E4">E4</option>

                        </select>         
                        <span asp-validation-for="Grade" class="text-bg-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SkillSetRequired" class="form-label">Skills Required:</label><br />
                        <input type="text" asp-for="SkillSetRequired" placeholder="Enter skills required" class="form-control" />
                        <span asp-validation-for="SkillSetRequired" class="text-bg-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ApprovedDate" class="form-label">Approved Date:</label><br />
                        <input type="date" asp-for="ApprovedDate" placeholder="Approved Date" class="form-control" />
                        <span asp-validation-for="ApprovedDate" class="text-bg-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="No_Of_Positions" class="form-label">Positions Required :</label><br />
                        <input type="text" asp-for="No_Of_Positions" placeholder="postions required" class="form-control" />
                        <span asp-validation-for="No_Of_Positions" class="text-bg-danger"></span>
                    </div>


                     <div class="form-group">
                        <label asp-for="JobDescription" class="form-label">Enter Job Description :</label><br />
                        <textarea rows="5" asp-for="JobDescription" class="form-control" placeholder="Enter Job Description">@Model.JobDescription</textarea>
                        <span asp-validation-for="JobDescription" class="text-bg-danger"></span>
                    </div>



                    <br />

                    <div class="form-group">
                        @*<input type="submit" class="=btn btn-dark float-right" value="Add Property" />*@
                        <button type="submit" class="btn btn-dark" value="Add Domain">Update Domain</button>
                    </div>


                </form>

            </div>
        </div>
    </div>
</div>

@section Scripts{

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }
}

ART_MVC/Views/Domain/Index.cshtml
@model List<DomainViewModel>
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Index";
    var flag = true;
    var token = Context.Session.GetString("token");
    var empEmail = Context.Session.GetString("empEmail");
    int projectId = 0;
    if (ViewContext.RouteData.Values["id"] != null && ViewContext.RouteData.Values["id"].ToString() != null)
    {
        projectId = int.Parse(ViewContext.RouteData.Values["id"].ToString());
    }


}




<h2 class="text-center mt-4 mb-5">@ViewBag.projectName</h2>

<div class="row mt-5">

    <div class="col-md-2"></div>
    <div class="col-md-8 mt-4">
        <a asp-controller="Home" asp-action="Index" class="text-start btn btn-warning">Go to HomePage</a>

        <div class="row">
            <div class="col">
                <div class="col text-end">
                </div>
                <h3 class="mt-4">Domain Index</h3>
            </div>
            @if (empEmail != null)
            {


                <div class="col text-end">
                    <a asp-controller="Domain" asp-action="Create" asp-route-projectId="@projectId" class="btn btn-dark">Add new Domain</a>
                </div>
            }
        </div>
        <div class="row">
            <table class="table table-hover shadow">
                <thead>
                    <tr>
                       
                        <th>Domain Name</th>
                       
                        <th>Status</th>
                        <th>Positions Required</th>
                        @if (empEmail != null)
                        {

                            <th>Action</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count <= 0)
                    {
                        flag = false;
                    }
                    @foreach (var item in Model)
                    {


                        <tr>
                           
                            <td>@item.DomainName</td>
                           
                            <td>@item.Status</td>
                            <td>@item.No_Of_Positions</td>
                            @if (empEmail != null)
                            {

                                <td>
                                    <a asp-controller="Domain" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                    <a asp-controller="Domain" asp-action="Edit" asp-route-id="@item.Id">Customize</a> |
                                    <a asp-controller="Domain" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                </td>
                            }

                        </tr>

                    }
                </tbody>
            </table>
            @if (!flag)
            {
                <h3>NO Records Found!</h3>
            }
        </div>
    </div>

</div>